# Dockerfile para MongoDB

# Usamos la imagen oficial de MongoDB como base
FROM mongo:6.0

# Exponer el puerto por defecto de MongoDB
EXPOSE 27017

# Definimos el comando de inicio, aunque el contenedor usa el entrypoint predeterminado de MongoDB
CMD ["mongod"]
