import type { ApiMemberDoc } from "../lib/LibModule";
import type { ScriptBinding } from "../bindings/scriptBindings";

/**
 * Generate a `zettelflow.d.ts` from the API manifest (#352).
 *
 * The `zf` API is invisible outside the plugin: library scripts under the JS-library folder are `.js`
 * files edited in VS Code or any other editor, where `zf` is an untyped mystery. This emits the
 * declarations that make it known there, from the **same manifest** the completions and the reference
 * page read — so the three cannot describe different APIs.
 *
 * Pure: descriptors in, TypeScript source out. No Obsidian, no file system.
 */

/** TypeScript identifiers a generated signature may use without us declaring them. */
const BUILT_IN_TYPES = new Set([
    "string", "number", "boolean", "void", "unknown", "any", "null", "undefined", "never", "object",
    "Promise", "Array", "Record", "Date", "Map", "Set", "Readonly", "Partial",
]);

/** Indentation for one nesting level. */
const INDENT = "    ";

interface TypeTree {
    /** Members declared at this level: name → signature. */
    members: Map<string, { signature: string; summary: string }>;
    /** Nested namespaces. */
    children: Map<string, TypeTree>;
}

function emptyTree(): TypeTree {
    return { members: new Map(), children: new Map() };
}

/** Fold the flat manifest (`zf.knowledge.debt`) into the nested shape a declaration needs. */
function buildTree(members: readonly ApiMemberDoc[]): TypeTree {
    const root = emptyTree();
    for (const member of members) {
        const segments = member.path.split(".");
        if (segments[0] !== "zf" || segments.length < 2) continue;
        const name = segments[segments.length - 1];

        let node = root;
        for (const segment of segments.slice(1, -1)) {
            if (!node.children.has(segment)) node.children.set(segment, emptyTree());
            node = node.children.get(segment) as TypeTree;
        }
        node.members.set(name, { signature: member.signature, summary: member.summary });
    }
    return root;
}

/** Capitalised identifiers referenced by a signature that we have to declare as opaque. */
function referencedTypes(members: readonly ApiMemberDoc[]): string[] {
    const found = new Set<string>();
    for (const member of members) {
        for (const match of member.signature.matchAll(/\b([A-Z][A-Za-z0-9_]*)\b/g)) {
            if (!BUILT_IN_TYPES.has(match[1])) found.add(match[1]);
        }
    }
    return [...found].sort();
}

function renderTree(node: TypeTree, depth: number): string[] {
    const pad = INDENT.repeat(depth);
    const lines: string[] = [];

    for (const [name, member] of [...node.members].sort(([a], [b]) => a.localeCompare(b))) {
        lines.push(`${pad}/** ${member.summary} */`);
        lines.push(`${pad}${name}: ${member.signature};`);
    }
    for (const [name, child] of [...node.children].sort(([a], [b]) => a.localeCompare(b))) {
        lines.push(`${pad}${name}: {`);
        lines.push(...renderTree(child, depth + 1));
        lines.push(`${pad}};`);
    }
    return lines;
}

/** What the live API adds that the manifest cannot know: the user's own scripts and integrations. */
export interface DynamicNamespaces {
    /** Function names loaded from the JS-library folder. */
    userScripts: readonly string[];
    /** Whether Dataview / Templater were present when the types were generated. */
    dataview: boolean;
    templater: boolean;
}

/**
 * Emit the declaration file.
 *
 * Return types are declared as opaque aliases rather than published shapes: ZettelFlow's internal
 * types are not a public contract, and pinning them here would freeze them. What the file exists to
 * give you is **the members and their arguments**, which is what an editor needs to help you write.
 */
export function generateTypeDeclarations(
    members: readonly ApiMemberDoc[],
    bindings: readonly ScriptBinding[],
    dynamic: DynamicNamespaces
): string {
    const tree = buildTree(members);
    injectDynamic(tree, dynamic);

    const lines: string[] = [
        "// Generated by ZettelFlow — do not edit.",
        "//",
        "// Declarations for the `zf` script API, so your editor knows it while you write library",
        "// scripts. Regenerate from Settings → Developer after adding a script or updating the plugin.",
        "",
        "// ZettelFlow's internal result shapes are not a published contract, so they are declared",
        "// opaque here. What this file gives you is the members and their arguments.",
    ];

    const opaque = referencedTypes(members);
    for (const name of opaque) lines.push(`type ${name} = any;`);
    if (opaque.length > 0) lines.push("");

    lines.push("declare const zf: {");
    lines.push(...renderTree(tree, 1));
    lines.push("};");
    lines.push("");

    lines.push("// The other variables a script receives. Which of these are in scope depends on the");
    lines.push("// surface — see the ZettelFlow docs.");
    for (const binding of bindings) {
        if (binding.name === "zf") continue;
        lines.push(`/** ${binding.type} */`);
        lines.push(`declare const ${binding.name}: any;`);
    }
    lines.push("");

    return lines.join("\n");
}

/** The node at a dotted path, creating the namespaces on the way. */
function nodeAt(root: TypeTree, path: readonly string[]): TypeTree {
    let node = root;
    for (const segment of path) {
        if (!node.children.has(segment)) node.children.set(segment, emptyTree());
        node = node.children.get(segment) as TypeTree;
    }
    return node;
}

/**
 * Fold in what only the *live* API knows: the user's own library scripts, and whichever integrations
 * are installed. This is why regenerating after adding a script picks it up — and why the file is
 * generated on demand rather than shipped with the plugin.
 */
function injectDynamic(tree: TypeTree, dynamic: DynamicNamespaces): void {
    const user = nodeAt(tree, ["internal", "user"]);
    for (const name of dynamic.userScripts) {
        user.members.set(name, {
            signature: "(...args: any[]) => any",
            summary: "Your own function from the JS-library folder.",
        });
    }

    if (dynamic.dataview || dynamic.templater) {
        const external = nodeAt(tree, ["external"]);
        if (dynamic.dataview) {
            external.members.set("dv", { signature: "any", summary: "The Dataview plugin API." });
        }
        if (dynamic.templater) {
            external.members.set("tp", {
                signature: "{ user: Record<string, any> }",
                summary: "Templater user scripts.",
            });
        }
    }
}
