import esbuild from "esbuild";
import {sassPlugin} from "esbuild-sass-plugin";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const vaultMode = (process.argv[2] === "vault");

// Verify .vault-path exists before starting vault-mode watcher
if (vaultMode) {
    const rootDir = path.dirname(fileURLToPath(import.meta.url));
    const vaultPathFile = path.join(rootDir, ".vault-path");
    if (!fs.existsSync(vaultPathFile)) {
        console.error(
            "[dev:vault] No .vault-path file found.\n" +
            "Create one with the absolute path to your plugin directory:\n" +
            "  echo C:\\YourVault\\.obsidian\\plugins\\zettelflow > .vault-path"
        );
        process.exit(1);
    }
}

function deployToVault() {
    try {
        execFileSync(process.execPath, ["scripts/deploy-vault.mjs"], { stdio: "inherit" });
    } catch {
        // deploy-vault already logged the error
    }
}

// Plugin that copies to vault after each successful build
const vaultDeployPlugin = {
    name: "vault-deploy",
    setup(build) {
        build.onEnd((result) => {
            if (result.errors.length === 0) deployToVault();
        });
    },
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
      "obsidian",
      "electron",
      "@codemirror/autocomplete",
      "@codemirror/closebrackets",
      "@codemirror/collab",
      "@codemirror/commands",
      "@codemirror/comment",
      "@codemirror/fold",
      "@codemirror/gutter",
      "@codemirror/highlight",
      "@codemirror/history",
      "@codemirror/language",
      "@codemirror/lint",
      "@codemirror/matchbrackets",
      "@codemirror/panel",
      "@codemirror/rangeset",
      "@codemirror/rectangular-selection",
      "@codemirror/search",
      "@codemirror/state",
      "@codemirror/stream-parser",
      "@codemirror/text",
      "@codemirror/tooltip",
      "@codemirror/view",
      "@codemirror/basic-setup",
      "@lezer/common",
      "@lezer/highlight",
      "@lezer/lr",
      ...builtins,
    ],
	format: "cjs",
	target: "ES6",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	minify: prod ? true : false,
	treeShaking: true,
	outfile: "dist/main.js",
	loader: {
        ".ttf": "file",
    },
    plugins: vaultMode ? [vaultDeployPlugin] : [],
});
const styles = await esbuild.context({
    entryPoints: ["src/styles/main.scss"],
    bundle: true,
    outfile: "dist/styles.css",
    plugins: [sassPlugin(), ...(vaultMode ? [vaultDeployPlugin] : [])],
});

if (prod) {
	await context.rebuild();
    await styles.rebuild();
	process.exit(0);
} else {
    if (vaultMode) {
        console.log("[dev:vault] Watching — artifacts will be deployed to vault on each rebuild.");
    }
	await context.watch();
    await styles.watch();
}
