site_name: ZettelFlow
repo_url: https://github.com/RafaelGB/Obsidian-ZettelFlow
edit_uri: edit/master/docs/
theme:
  name: material
  navigation.instant: true
  logo: resources/obsidian.png
  icon:
    repo: fontawesome/brands/github-alt
plugins:
  - search
nav:
  - 1. Home: index.md
  - 2. Actions:
      - 2.1 Prompt: actions/Prompt.md
      - 2.2 Number: actions/Number.md
      - 2.3 Checkbox: actions/Checkbox.md
      - 2.4 Calendar: actions/Calendar.md
      - 2.5 Selector: actions/Selector.md
      - 2.6 Dynamic Selector: actions/DynamicSelector.md
      - 2.7 Tags: actions/Tags.md
      - 2.8 Backlink: actions/Backlink.md
      - 2.9 CssClasses: actions/CssClasses.md
      - 2.10 TaskManagement: actions/TaskManagement.md
      - 2.11 Script: actions/Script.md
  - 3. Vault Hooks:
      - 3.1 Property Hooks:
          - 3.1.1 Overview: vault-hooks/property-hooks/overview.md
          - 3.1.2 Configuration: vault-hooks/property-hooks/configuration.md
          - 3.1.3 Examples: vault-hooks/property-hooks/examples.md
      - 3.2 Folder Automation: vault-hooks/OnCreate.md
  - 4. How to Contribute:
      - 4.1 Wiki: how-to-contribute/Wiki.md
  - 5. API: api/ZettelFlowAPI.md
extra_javascript:
  - "extra_javascript/navigationInstant.js"
